// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Folder struct {
	Fid   string  `json:"fid"`
	Name  string  `json:"name"`
	Pages []*Page `json:"pages"`
}

type ListComponent struct {
	ID        string      `json:"id"`
	Title     string      `json:"title"`
	ListItems []*ListItem `json:"listItems"`
}

func (ListComponent) IsFolderComponent() {}

type ListComponentInput struct {
	ID        string           `json:"id"`
	ListItems []*ListItemInput `json:"listItems"`
}

type ListItem struct {
	ID       string  `json:"id"`
	Title    string  `json:"title"`
	Response *string `json:"response"`
}

type ListItemInput struct {
	ID       string `json:"id"`
	Response string `json:"response"`
}

type OutlineChild struct {
	ID               string          `json:"id"`
	Title            string          `json:"title"`
	RequiresResponse bool            `json:"requiresResponse"`
	Response         *string         `json:"response"`
	Children         []*OutlineChild `json:"children"`
}

type OutlineComponent struct {
	ID       string          `json:"id"`
	Title    string          `json:"title"`
	Children []*OutlineChild `json:"children"`
}

func (OutlineComponent) IsFolderComponent() {}

type OutlineComponentInput struct {
	ID        string             `json:"id"`
	Responses []*OutlineResponse `json:"responses"`
}

type OutlineResponse struct {
	ID       string `json:"id"`
	Response string `json:"response"`
}

type Page struct {
	ID         string            `json:"id"`
	Components []FolderComponent `json:"components"`
}

type PictureComponent struct {
	ID       string         `json:"id"`
	Title    string         `json:"title"`
	Pictures []*PictureItem `json:"pictures"`
}

func (PictureComponent) IsFolderComponent() {}

type PictureComponentInput struct {
	ID       string              `json:"id"`
	Pictures []*PictureItemInput `json:"pictures"`
}

type PictureItem struct {
	ID                 string  `json:"id"`
	PictureStaticURL   *string `json:"pictureStaticUrl"`
	NeedsResponseText  bool    `json:"needsResponseText"`
	PictureResponseURL *string `json:"pictureResponseUrl"`
	TextResponse       *string `json:"textResponse"`
}

type PictureItemInput struct {
	ID                 string  `json:"id"`
	PictureResponseURL *string `json:"pictureResponseUrl"`
	TextResponse       *string `json:"textResponse"`
}

type SaveAssignmentInput struct {
	ListComponents    []*ListComponentInput    `json:"listComponents"`
	OutlineComponents []*OutlineComponentInput `json:"outlineComponents"`
	PictureComponents []*PictureComponentInput `json:"pictureComponents"`
	TableComponents   []*TableComponentInput   `json:"tableComponents"`
}

type TableCell struct {
	Row      int     `json:"row"`
	Column   int     `json:"column"`
	Response *string `json:"response"`
}

type TableCellInput struct {
	Row      int     `json:"row"`
	Column   int     `json:"column"`
	Response *string `json:"response"`
}

type TableComponent struct {
	ID      string       `json:"id"`
	Title   string       `json:"title"`
	Rows    []string     `json:"rows"`
	Columns []string     `json:"columns"`
	Cells   []*TableCell `json:"cells"`
}

func (TableComponent) IsFolderComponent() {}

type TableComponentInput struct {
	ID    string            `json:"id"`
	Cells []*TableCellInput `json:"cells"`
}

type User struct {
	Oid   string `json:"oid"`
	Name  string `json:"name"`
	Role  string `json:"role"`
	Email string `json:"email"`
}
